spring:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  batch:
    job:
      enabled: false
  
logging:
  level:
    com.p6spy: DEBUG